version: "3"
services:
  web:
    build: .
    links:
      - redis
    ports:
      - "1443:1443"
    environment:
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_DB: ${REDIS_DB:-0}
      BASE_URL: ${BASE_URL:-http://localhost:1443}
      DETECT_BASE_URL: ${DETECT_BASE_URL:-false}
      MAX_FILE_SIZE: ${MAX_FILE_SIZE:-2147483648}
      MAX_FILES_PER_ARCHIVE: ${MAX_FILES_PER_ARCHIVE:-64}
      MAX_EXPIRE_SECONDS: ${MAX_EXPIRE_SECONDS:-604800}
      MAX_DOWNLOADS: ${MAX_DOWNLOADS:-100}
      DOWNLOAD_COUNTS: ${DOWNLOAD_COUNTS:-10,1,2,5,10,15,25,50,100,1000}
      EXPIRE_TIMES_SECONDS: ${EXPIRE_TIMES_SECONDS:-3600,86400,604800,2592000,31536000}
      DEFAULT_DOWNLOADS: ${DEFAULT_DOWNLOADS:-1}
      DEFAULT_EXPIRE_SECONDS: ${DEFAULT_EXPIRE_SECONDS:-86400}

      FILE_DIR: ${FILE_DIR:-/uploads}
      # S3-related options (use only if needed)
      S3_BUCKET: ${S3_BUCKET:-}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
      S3_ENDPOINT: ${S3_ENDPOINT:-}
      S3_USE_PATH_STYLE_ENDPOINT: ${S3_USE_PATH_STYLE_ENDPOINT:-false}
      # Google bucket (use only if needed)
      #GCS_BUCKET: ${GCS_BUCKET:-}

      # Branding options
      UI_COLOR_PRIMARY: ${UI_COLOR_PRIMARY:-#0a84ff}
      UI_COLOR_ACCENT: ${UI_COLOR_ACCENT:-#003eaa}
      UI_CUSTOM_CSS: ${UI_CUSTOM_CSS:-}
      CUSTOM_FOOTER_TEXT: ${CUSTOM_FOOTER_TEXT:-}
      CUSTOM_FOOTER_URL: ${CUSTOM_FOOTER_URL:-}
  redis:
    image: redis:alpine
  selenium-firefox:
    image: b4handjr/selenium-firefox
    ports:
      - "${VNC_PORT:-5900}:5900"
    shm_size: 2g
    volumes:
      - .:/code
